### ISSUE TITLE
Output tokens?

### ISSUE THREAD

**Issue by tmikaeld** [01-ai/Yi-Coder#6]
What's the max output tokens the model can produce?

**Comment by tmikaeld** [comment]
Seems to be 1024, can't get it to go over that

**Comment by Haijian06** [comment]
Hi @tmikaeld 👋 Our model currently supports a maximum context length of 128k tokens. Larger context windows (higher max_token values) require significantly more GPU memory. In the provided examples, we've used a context length of 1024 tokens to make it easier for more people to quickly experience the capabilities of the model.

**Comment by tmikaeld** [comment]
When i try it with ollama, the model doesnt output more than 1024. Do you know what can cause this?

**Comment by tmikaeld** [comment]
This isn't very clear anywhere, but in Continue extension for VSCode, add:
```json
{
 "completionOptions": {
        "maxTokens": 4096
 }
}
 ```
 
 On the model config parameters for Ollama.
